### ISSUE TITLE
[FR] Set machine IP automaticlly without refershing page

### ISSUE THREAD

**Issue by HitmanAlharbi** [echoCTF/echoCTF.RED#1324]
**Is your feature request related to a problem? Please describe.**

When power up a machine, I must do a refresh to the machine's page to show the machine IP

**Describe the solution you'd like**

JS code to set IP automatically, or do a simple refresh to the page

**Additional context**
![Screenshot_1](https://github.com/user-attachments/assets/2ada5680-6e08-451c-938e-eb01507ee6b3)

https://github.com/echoCTF/echoCTF.RED/blob/1ab2ac6574a86f596f1973aa64294271a82940a4/backend/commands/CronController.php#L408

**Comment by proditis** [comment]
Already working towards bringing this functionality to the platform :heart: 
![image](https://github.com/user-attachments/assets/cdbf80bd-5eb6-4a14-b78f-96a0f5cf7a63)

Will be part of the next update :crossed_fingers:

**Comment by proditis** [comment]
![liveupdate](https://github.com/user-attachments/assets/bf9c5a90-989a-4c78-b9bb-0236cb366b45)
testing now :)

**Comment by proditis** [comment]
It will be up on the next platform update :) thank you for reporting this brother :heart:
