### ISSUE TITLE
OpenVPN/Error: Creating default object from an empty value

### ISSUE THREAD

**Issue by abdulr7mann** [echoCTF/echoCTF.RED#192]
## commands
```bash
$ git clone https://github.com/echoCTF/echoCTF.RED.git
$ cd echoCTF.RED
$ docker-compose pull
$ docker-compose up
```
first image: it goes into loop of the same error
![a](https://cdn.discordapp.com/attachments/746500634731348018/754137906918195291/unknown.png)
second: stops at OpenVPN Error
![b](https://cdn.discordapp.com/attachments/746500634731348018/754255856157065226/unknown.png)

**Comment by proditis** [comment]
Hi @abdulr7mann thanks for the issue. I will investigate and get back to you soon.

In the mean time can you please try to cleanup the existing echoctf volumes and try to the `docker-compose build` option
```sh
docker volume rm echoctfred_data-challenges echoctfred_data-mysql echoctfred_data-openvpn
GITHUB_OAUTH_TOKEN=YOUR_TOKEN docker-compose build
```

**Comment by abdulr7mann** [comment]
Cleaned it
```
docker volume prune -f
docker system prune
GITHUB_OAUTH_TOKEN=myPersonalToken docker-compose build
```
same problem
![b](https://cdn.discordapp.com/attachments/746500634731348018/754255856157065226/unknown.png)
