### ISSUE TITLE
Feature Request: writeups on profile

### ISSUE THREAD

**Issue by 0xRar** [echoCTF/echoCTF.RED#368]
Display the writeups the user wrote for any challenge or a target on the user's profile **`https://echoctf.red/profile/me`**
, with `Challenges solved` &  `Headshots` ...

**Comment by proditis** [comment]
Is this what you had in mind ?
![writeup on target](https://user-images.githubusercontent.com/4373752/113945805-c57a7380-980f-11eb-87aa-618971c23d02.png)

**Comment by 0xRar** [comment]
hmm. isn't this what's on the platform rn?  

but yeah something like this

**Comment by 0xRar** [comment]
# Samples:
![image](https://user-images.githubusercontent.com/33517160/116261493-6067cd00-a780-11eb-86f3-c61f9e424a8f.png)

![image](https://user-images.githubusercontent.com/33517160/116261661-88efc700-a780-11eb-9cee-87f655016e47.png)

![image](https://user-images.githubusercontent.com/33517160/116261742-9c9b2d80-a780-11eb-8756-757bd2f8834a.png)
