### ISSUE TITLE
Filter in social media usernames

### ISSUE THREAD

**Issue by HitmanAlharbi** [echoCTF/echoCTF.RED#433]
Hey guys,

The social media usernames accept bad characters like ( / ? & )

And this help the attacker to redirect any user click on the social media logo to another page

Example in twitter username: intent/tweet?text=Can+we+drink+a+coffee?

![Screenshot_1](https://user-images.githubusercontent.com/36328177/119562218-c3b04380-bdae-11eb-9182-f027c06d4b61.png)

**Comment by proditis** [comment]
* Usernames containing the words *Twitter* or *Admin* cannot be claimed. No account names can contain *Twitter* or *Admin* unless they are official Twitter accounts.
* Your username cannot be longer than 15 characters.
* A username can only contain alphanumeric characters (letters A-Z, numbers 0-9) with the exception of underscores `_`.

**Comment by HitmanAlharbi** [comment]
Youtube username=../watch?v=_Yhyp-_hX2s

**Comment by proditis** [comment]
Fixed on master branch closing for release.
