### ISSUE TITLE
Is the docker-compose network part, missing the OpenVPN network ?

### ISSUE THREAD

**Issue by Infouzi** [echoCTF/echoCTF.RED#475]
Hi there, i hope you are not tired of me yet ;p

So, during the setup phase (in the tutorial [https://echoctfred.readthedocs.io/DOCKER-COMPOSE/](url)), there is a mention of `4 netowrks` in the docker containers:

### the containers
<img width="383" alt="Capture d’écran 2021-12-05 à 9 21 16 AM" src="https://user-images.githubusercontent.com/61884413/144739233-8fcdaeea-96c8-49a3-929a-ddf7395a1849.png">

So, since, the last one (the OPENVPN network) doesn't exist, i was wondering if something is missing ?

Also and since we are here talking about VPN, when it is said to **set the vpngw** "Set the IP or FQDN for the VPN server that participants will have to connect through openvpn", `what is the correct IP address to set ?` since it has 3 known addresses.

**Comment by proditis** [comment]
Hi @Infouzi, i'm glad you stayed. Nop not tired at all buddy, :smile: keep em coming.

So this network is not a docker network but rather it refers to the "network range" that openvpn will assign IP's to the connected players. When a user connects through OpenVPN it will be assigned one address from this range.

The second refers to the public IP that your OpenVPN server will be accessible at. This IP is used on the generation of the connection pack that the players download from their profile.

In general everything in `*_public` can be accessible by players, `*_private` is used for communication between systems and components and `*_targets` is our targets & challenges range.

I hope this helps. 

PS: Thank you for your reports its been a pleasure dealing with them :smiley:

**Comment by Infouzi** [comment]
Glad to hear that. 🙏

For the first one, that's what i told myself in the first place, but i needed to be sure about this. Thanks.

About the second one, it's more or less what i have understood, great. The docs was (is still) good, no problem. But, in order to be 100% sure, i still need to know, this ip, is not in the "public ip range" but should be my host ip addr ? (Since i'm starting with the all in one installation)

**Comment by proditis** [comment]
If you have a suggestion on how we could phrase this better please go ahead and share it. Its extremely hard for me to document things from the perspective of the new user of the platform as I am also the main developer. 

I feel that all of your questions could have been addressed if we worded this better in the docs, so please by all means help out :smile: if you have a suggestion.

In the meantime I will update the relevant sections of the documentation with the extra information I provided here.

**Comment by proditis** [comment]
Not sure if i answered your last part but just to clarify:
* if your users are going to be connecting directly to this host then yes add the host IP. This assumes that your clients are on the same "lan" with your host.
* if your users connect through a port forwarding or nat  (eg through internet) then you add the public IP address of your gateway. 

I hope this clears a bit more of the confusion.

**Comment by Infouzi** [comment]
Oh thank you, i was just too drown in my vpn tests that i forget to answer back.

So, as it is for now:

- I managed to connect to the vpn by setting my host IP. Until here, everything is nice, and i have a private ip (`10.10.0.6`)
- However, when i try to connect to the first machine (ip: `10.0.160.2`), i can't.

Even if i am understanding that since there is a route that redirect the traffic from "10.10.0.0/16" (vpn private ip range) to "10.0.160.1", as long as i am with the vpn, i can access targets machines.

I'm still on it

**Comment by Infouzi** [comment]
> If you have a suggestion on how we could phrase this better please go ahead and share it. Its extremely hard for me to document things from the perspective of the new user of the platform as I am also the main developer.
> 
> I feel that all of your questions could have been addressed if we worded this better in the docs, so please by all means help out 😄 if you have a suggestion.
> 
> In the meantime I will update the relevant sections of the documentation with the extra information I provided here.

Oh, don't you worry, i know whtat it is to develop AND document at the same time :p

Anyways, the explanation (even in the docs) was sufficient and clear. Thanks.

**Comment by proditis** [comment]
> * I managed to connect to the vpn by setting my host IP. Until here, everything is nice, and i have a private ip (`10.10.0.6`)

Make sure you also get a route for the 10.0.160.x network when connected to the VPN and that the route is attached to the TUN interface.

> * However, when i try to connect to the first machine (ip: `10.0.160.2`), i can't.

If the network routes are being pushed properly by openvpn then i suspect one of two things, iptables or local route missing. The local route may be deleted in some cases when you restart the containers, so double check to make sure its there.

Let me know if this helps

**Comment by Infouzi** [comment]
Hi @proditis ,

I finally managed to get me some time to try and figure out what is happening. So, here's the situation:

### My vpn ip address + the gateway that it uses:
<img width="434" alt="vpn-ip-gateway" src="https://user-images.githubusercontent.com/61884413/145174877-db6265de-0dc0-4356-aeec-3802b070fdc1.png">

### The routing table status while being connected to the vpn
<img width="462" alt="route-table" src="https://user-images.githubusercontent.com/61884413/145174983-f92ea122-8cdc-4fcf-919e-0bede76e7a87.png">

I suspect the last entry in the routing table to be the problem, but i don't want to delete it just yet.

Any help would be appreciated, thanks. ˆˆ

**Comment by proditis** [comment]
Just to clarify both outputs are from the client system while connected to the VPN right? In that case the last entry seems like the standard entry openvpn adds for the tun.

What confuses me is the route to `en1`. I cant figure out why traffic towards `10.10/16` is routed through the `10.0.160.1`? 
What type of system is this (vm, container)? What other networks is connected to? Also is this route the manual command mentioned in the docs? If so then this route will have to be executed on the system running the docker containers and not the vpn client.

Keep in mind that if you're trying to test everything from the same system (including vpn server and vpn client) using only containers you are going to face a lot of difficulties.

**Comment by proditis** [comment]
Closing this since there are no updates. I assume everything got fixed :smile: 

If you still have issues feel free to open a new issue.

**Comment by Infouzi** [comment]
> utputs are from the client system while connected to the VPN r

I m sorry i didn't came back with a feedback earlier, but better late than never :stuck_out_tongue_winking_eye:  A lot happened this year that obliged me to shift my focus on other projects and it happened just at the same period as i was testing last year.

Because of that, i ended up forgetting that i even started setting up this once.

Anyway, wish you all the best :heart: and a huge thanks for your previous support. :100:
