### ISSUE TITLE
We have cases were both ondemand and private IP's appear making it confusing for the player

### ISSUE THREAD

**Issue by proditis** [echoCTF/echoCTF.RED#656]
Reported on our discord by https://echoctf.red/profile/1653099
![image](https://user-images.githubusercontent.com/4373752/174251475-9f130b43-2904-4aea-a29b-97ff8a332766.png)

**Comment by 0xRar** [comment]
oh yeah i think i noticed something like this also where the private instance is not running so the ip shows up as 0.0.0.0, but on the top shows the ip of the machine.

**Comment by 0xRar** [comment]
not sure if it can help solve the problem but, i thought of a suggestion; what if every ip is set to 0.0.0.0 but when connected to the vpn shows the ip of the machine (not sure if its even possible)
