### ISSUE TITLE
New Feature Request: Personalizing of Logos

### ISSUE THREAD

**Issue by harperaa** [echoCTF/echoCTF.RED#73]
It is requested that on backend, the admin be able to establish the local logo desired for the server.  This should be settable and persistent after reboots, so it may need to be linked into the volume for persistence in dockers.

**Comment by proditis** [comment]
Added a volume mapping on `docker-compose.yml` of `./themes/images` to the `backend/web/images` and `frontend/web/images`. 

You can modify the default logos under `./themes/images` to have them persist across reboots.
