### ISSUE TITLE
New Feature Request: Personalizing of Target Logo

### ISSUE THREAD

**Issue by harperaa** [echoCTF/echoCTF.RED#74]
It is requested that 
1. a default logo be used for new targets, then on the backend 
2. an admin can change that logo from the backend web interface and those settings be persistent, over reboots or restarts of containers.

**Comment by proditis** [comment]
Added default logo for targets and its now also part of the ./themes/images volume. So you can add target logos and have them persist.

**Comment by proditis** [comment]
@harperaa Can you please confirm if the implemented solution is ok or not ok?
